### ISSUE TITLE
errata: Chapter 2 

### ISSUE THREAD

**Issue by khosrogh** [PacktPublishing/40-Algorithms-Every-Programmer-Should-Know#3]
I am reading chapter two. On **page 43**, the output of the code below should be different:

```
[1]: yellow = {'dandelions', 'fire hydrant', 'leaves'}
[2]: red = {'fire hydrant', 'blood', 'rose', 'leaves'}
[3]:  yellow&red
```

In the book, it is written **{'fire hydrant'}**, but it should be **{'leaves', 'fire hydrant'}**.

**Comment by rajat-packt** [comment]
Thanks @khosrogh for letting us know of this!
We have updated the README to reflect this erratum, so that it may help other readers.

**Comment by khosrogh** [comment]
Thanks for the reflection @rajat-packt .
I've also found another issue in chapter 2, should I mention it here or open a separate issue for every issue I find? For example in chapter 3, I've found 3 typos, should I address them in a single issue?
Thanks for the reply.

**Comment by rajat-packt** [comment]
@khosrogh It would be great if you can list all the issues together, if possible. That way we can get them rectified all at once.
Feel free to open a new issue and list everything there or you can open more issues later, and we'll do our best to get them solved asap!
